{{- $altNames := list ( printf "%s.%s" .Values.kubearmorAnnotationManager.name .Release.Namespace ) ( printf "%s.%s.svc" .Values.kubearmorAnnotationManager.name .Release.Namespace ) -}}
{{- $ca := genCA .Values.kubearmorAnnotationManager.name  1095 -}}
{{- $cert := genSignedCert .Values.kubearmorAnnotationManager.name nil $altNames 1095 $ca -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kubearmorAnnotationManager.name }}
  labels:
    kubearmor-app: {{ .Values.kubearmorAnnotationManager.name }}
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.kubearmorAnnotationManager.name }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ $ca.Cert | b64enc}}
    service:
      name: {{ .Values.kubearmorAnnotationManager.name }}
      namespace: kube-system
      path: /mutate-pods
      port: 443
  failurePolicy: {{ .Values.kubearmorAnnotationManager.mutation.failurePolicy }}
  matchPolicy: Equivalent
  name: annotation.kubearmor.com
  objectSelector:
    matchExpressions:
    - key: kubearmor-app
      operator: DoesNotExist
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
  sideEffects: NoneOnDryRun
  timeoutSeconds: 10