{{- if .Values.kubearmorrelay.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kubearmor
spec:
  ports:
  - port: 32767
    protocol: TCP
    targetPort: 32767
  selector:
    kubearmor-app: kubearmor-relay
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubearmor-app: kubearmor-annotation-manager
  name: {{ .Values.kubearmorAnnotationManager.name }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 9443
  selector:
    kubearmor-app: kubearmor-annotation-manager